DROP TABLE users;
CREATE TABLE users (
id int NOT NULL AUTO_INCREMENT,
phone_number CHARACTER(10) NOT NULL UNIQUE,
os CHARACTER(1) NOT NULL,
pn_token VARCHAR(255),
PRIMARY KEY (id)
);

-- TEST
-- INSERT INTO users (phone_number, os) VALUES ("6969696969", 1);