DROP TABLE users;
CREATE TABLE users (
id int NOT NULL AUTO_INCREMENT,
phone_number CHARACTER(10) NOT NULL UNIQUE,
os BINARY NOT NULL DEFAULT 0,
pn_enabled BOOLEAN NOT NULL DEFAULT FALSE,
pn_token VARCHAR(255),
PRIMARY KEY (id)
);

-- TEST
-- INSERT INTO users (phone_number, os) VALUES ("6969696969", 1);